bosses = ['Magmaw',
          'Omnotron Defense System',
          'Chimaeron',
          'Atramedes',
          'Maloriak',
          "Nefarian's End",
          'Conclave of Wind',
          "Al'Akir",
          'Halfus Wyrmbreaker',
          'Theralion and Valiona',
          'Ascendant Council',
          "Cho'gall",
          'Sinestra',
          'Baleroc',
          'Shannox',
          "Beth'tilac",
          'Lord Rhyolith',
          'Alysrazor',
          'Majordomo Staghelm',
          'Ragnaros'
          ]
